#!/usr/bin/env bash

#原作：zdszf
##
#Auth：逸笙
#用法1：bash hostloc.sh username password
#用法2：bash hostloc.sh accountfile

#微信开发者服务，不用就留空，关注wxpusher获得ID
#可多个，以空格分开
we_no_id=""

declare -A userpsw
declare -A precredit
declare -A aftcredit
declare -A getcredit
declare -A userlevel
declare -A userUID

#get username&password
if [ $# -eq 2 ]; then
  userpsw["$1"]="$2"
fi
if [ $# -eq 1 ]; then
  if [ -s "$1" ]; then
    usrarry=(`cat $1 | awk '{print $1}'`)
    pswarry=(`cat $1 | awk '{print $2}'`)
    for((u=0;u<${#usrarry[*]};u++))
    do
      userpsw["${usrarry[$u]}"]="${pswarry[$u]}"
    done
  else
    echo 文件 $1 不存在
    exit 1
  fi
fi

# workdir
workdir="/root/hostlog"
[[ ! -d "${workdir}" ]] && mkdir ${workdir}
logpath="/root/hostlog/"
precookiefile="/root/hostlog/precookiefile"

UA="Mozilla/5.0+(Windows+NT+6.2;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/74.0.3729.131+Safari/537.36"

delaytime=25

function preconfig() {
  curl -s -H "$UA" "https://www.hostloc.com/" | grep "slowAES">${workdir}/tmp
  if [ -s "${workdir}/tmp" ]; then
    echo "论坛开启了js-cookie验证"
    aa=`cat ${workdir}/tmp | awk -F 'a=toNumbers' '{print $2}' | awk -F '"' '{print $2}'`
    bb=`cat ${workdir}/tmp | awk -F 'b=toNumbers' '{print $2}' | awk -F '"' '{print $2}'`
    cc=`cat ${workdir}/tmp | awk -F 'c=toNumbers' '{print $2}' | awk -F '"' '{print $2}'`

    #提交abc的值给写好的无服务器函数计算
    L7FW=`curl -s "https://service-27buax72-1258064400.ap-hongkong.apigateway.myqcloud.com/release/nodejstest1?aa="$aa"&bb="$bb"&cc="$cc`
    #生成precookie文件
    echo '# Netscape HTTP Cookie File'>${precookiefile}
    echo '# http://curl.haxx.se/docs/http-cookies.html'>>${precookiefile}
    echo '# This file was generated by libcurl! Edit at your own risk.'>>${precookiefile}
    echo>>${precookiefile}
    echo -e 'www.hostloc.com\tFALSE\t/\tFALSE\t0\tL7FW\t'$L7FW>>${precookiefile}
  fi
  rm -f ${workdir}/tmp

  newuserspace=`curl -s -b ${precookiefile} https://www.hostloc.com/forum.php | grep -oE "欢迎新会员: <em><a href=\".*\" " | awk -F'\"' '{print $2}'`
  maxuid=`curl -s -b ${precookiefile} https://www.hostloc.com/${newuserspace} | grep "空间首页" | awk -F 'uid=' '{print $2}' | awk -F '&' '{print $1}'`
  tmpuid=$((maxuid-200))
}

function login() {
  echo -n $(date "+%Y-%m-%d %H:%M:%S %A") ${username} 登陆... 
  data="mod=logging&action=login&loginsubmit=yes&infloat=yes&lssubmit=yes&inajax=1&fastloginfield=username&username=$username&cookietime=$(shuf -i 1234567-7654321 -n 1)&password=$password&quickforward=yes&handlekey=ls"
  curl -s -H "$UA" -c ${workdir}/${cookiefile} -b ${precookiefile} --data "$data" "https://www.hostloc.com/member.php" | grep "hostloc" >/dev/null && echo "成功" || status="1"
  [[ $status -eq 1 ]] && echo 失败 && getcredit["$username"]="-1" && continue
  yourgroup=(`curl -s -H "$UA" -b ${workdir}/${cookiefile} "https://www.hostloc.com/forum.php" | grep "用户组" | awk -F ':' '{print $2}' | awk -F '<' '{print $1}'`)
  userlevel[${username}]=${yourgroup[0]}
  youruid=(`curl -s -H "$UA" -b ${workdir}/${cookiefile} "https://www.hostloc.com/home.php?mod=spacecp&ac=credit" | grep -oE "uid=\w*" | awk -F '[=]' '{print $2}'`)
  userUID[${username}]=${youruid[0]}
  echo $(date "+%F %T %A") "${userlevel[${username}]}(UID：${userUID[${username}]})"
}

function logout() {
  logoutlink=`curl -s -H "$UA" -b ${workdir}/${cookiefile} "https://www.hostloc.com/space-username-${user1}.html" | grep "退出" | awk -F '"' '{print $2}'`
  logoutlink=${logoutlink//&amp;/&}
  #echo ${logoutlink}
  echo -n $(date "+%Y-%m-%d %H:%M:%S %A")
  echo -n " ${user1} "
  curl -s -H "$UA" -b ${workdir}/${cookiefile} "https://www.hostloc.com/${logoutlink}" | grep -o "您已退出站点"
}

function randuid() {
  startuid=0
  enduid=${maxuid}
  while [ ${userUID[${username}]} -gt $startuid -a ${userUID[${username}]} -lt $enduid ]
  do
    #随机开始UID
    r=`head -200 /dev/urandom | cksum | cut -f1 -d" "`
    startuid=$((r%tmpuid+100))
    enduid=$((startuid+100))
  done

  #随机间隔时间
  delaytime=$((r%50+10))
  #delaytime=3
}

function credit() {
  creditall=$(curl -s -H "$UA" -b ${workdir}/${cookiefile} "https://www.hostloc.com/home.php?mod=spacecp&ac=credit&op=base" | grep -oE "积分: </em>\w*" | awk -F'[>]' '{print $2}')
  echo $(date "+%Y-%m-%d %H:%M:%S %A") 目前积分：${creditall}
}

function view() {
  a=0
  echo -n $(date "+%Y-%m-%d %H:%M:%S %A") 访问空间：
  echo 从$startuid开始，间隔${delaytime}s...
  for((i = $startuid; i <= $enduid; i++))
  do
    p=0 
    sleep ${delaytime}
    echo -n $(date "+%Y-%m-%d %H:%M:%S %A") ${i}
    curl -s -H "$UA" -b ${workdir}/${cookiefile} "https://www.hostloc.com/space-uid-$i.html" | grep -o "最近访客" >/dev/null && p=1 || echo " banlist"
    if [ $p -eq 1 ]; then
      ((a++))
      echo -e " ok，\t$a"
    fi
    [[ $a -eq 10 ]] && break
  done
  echo $(date "+%Y-%m-%d %H:%M:%S %A") 完成
}

#发送到微信，需要提前赋值we_no_id
#函数需要4个参数，标题、级别、内容、详细内容
function noticetowechat() {
  #echo $1,$2,$3,$4
  data1='{"userIds":['
  for weid in ${we_no_id}
  do
    data1=${data1}'"'${weid}'",'
  done
  data1=${data1:0:-1}
  data1=${data1}'],"template_id":"lpO9UoVZYGENPpuND3FIofNueSMJZs0DMiU7Bl1eg2c","data":{"first":{"value":"'
  data1=${data1}"$1"
  data1=${data1}'","color":"#000099"},"keyword1":{"value":"'
  data1=${data1}"$2"
  data1=${data1}'","color":"#ff00aa"},"keyword2":{"value":"'
  data1=${data1}"$3"
  data1=${data1}'","color":"#ff0000"},"keyword3":{"value":"'
  data1=${data1}"$(date "+%F %T %A")"
  data1=${data1}'","color":"#000000"},"remark":{"value":"'
  data1=${data1}"$4"
  data1=${data1}'","color":"#667766"}}}'
  curl -s -X POST "http://wxmsg.dingliqc.com/send" -d "${data1}" -H "Content-Type:application/json" | grep "处理成功" >/dev/null && echo '微信报告发送成功' || echo '微信发送失败'
}

function dellog() {
  cd $1
  n=`date +%Y%m%d`
  for a in $(ls *log.txt)
  do
    f=${a%%-*}
    #echo $f,$n
    s=$((n-f))
    [ $s -gt 8900 ] && rm -f $a
    if [ $s -lt 8800 ]; then
        [ $s -gt 100 ] && rm -f $a
    fi
  done
}

function main() {
  echo '~START~'
  preconfig
  for user1 in ${!userpsw[*]}
  do
    username=${user1}
    password=${userpsw[$user1]}
    cookiefile=h_${username}.cookie
    creditall=0
    
    login
    randuid
    credit
    precredit["$username"]=${creditall}
    view
    credit
    aftcredit["$username"]=${creditall}
    getcredit["$username"]=$((aftcredit[${username}]-precredit[${username}]))

    # exit
    logout

    # clean
    rm -f ${workdir}/${cookiefile}

    echo 
    sleep ${delaytime}
  done
  
  lnum=0
  for user1 in ${!getcredit[*]}
  do
    echo -e "UID:${userUID[$user1]},\t${user1},\t${userlevel[$user1]},\t${precredit[$user1]}\t+\t${getcredit[$user1]}\t=\t${aftcredit[$user1]}"
    remark=${remark}"UID:${userUID[$user1]},\t${user1},\t${userlevel[$user1]},\t${precredit[$user1]}\t+\t${getcredit[$user1]}\t=\t${aftcredit[$user1]}\n"
    [ ${getcredit[$user1]} -lt 20 ] && ((lnum++))
  done
  [ $lnum -eq 0 ] && stat1="正常" || stat1="有问题"
  [ -n "${we_no_id}" ] && noticetowechat 'HostLoc访问空间' "${lnum}" "${stat1}" "${remark}"

  dellog ${logpath}
  echo '~END~'
}

main
